# This is a TOML document.

server_host = "0.0.0.0"
server_port = "8080"

[cas]
service_url="http://127.0.0.1:8080"
server_url_prefix="http://127.0.0.1:2280/uuc"
exclude_urls="/api/open/*;/api/allow/*;/api/logout"


[mysql]
url="(127.0.0.1:3308)/good_job?charset=utf8mb4&parseTime=True&loc=Local"
username="root"
password="root"
maxOpenConns=20
connMaxLifetime=60000
maxIdle=15
